Update vue 3 getting started sample code
meilisearch/meilisearch-vue pull request #120
Opened 2022-10-07 07:03 UTC by amit-ksh

# Pull Request

## Related issue
Fixes #117 

## What does this PR do?
Update the vue 3 getting started sample code from vue 2 in README.md

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-10-07 07:03 UTC, bidoubiwa commented
Hello @amit-ksh,
Thank you very much for contributing to Meilisearch :heart:.
However, I am not available on the weekend, but I will be back on Monday :blush:.

*PS: This message was sent automatically!*

2022-10-18 10:30 UTC, bidoubiwa commented
Hey @amit-ksh ! Thanks for waiting, your PR flew under the radar! I'll be reviewing it ASAP!

2022-10-18 10:57 UTC, bidoubiwa commented
I tried your sample out but unfortunately it does not work. Any idea why?

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@meilisearch/instant-meilisearch/templates/basic_search.css" />
</head>

<body>
  <div id="app" class="wrapper">
    <ais-instant-search :search-client="searchClient" index-name="movies">
      <ais-configure :hits-per-page.camel="10" />
      <ais-search-box placeholder="Search here…" class="searchbox"></ais-search-box>
      <ais-hits>
        <div slot="item" slot-scope="{ item }">
          <ais-highlight :hit="item" attribute="title" />
        </div>
      </ais-hits>
    </ais-instant-search>
  </div>
</body>

<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-instantsearch/vue3/umd/index.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@meilisearch/instant-meilisearch/dist/instant-meilisearch.umd.min.js">
</script>

<script>
  const app = Vue
    .createApp({
      data() {
        return {
          searchClient: instantMeiliSearch('http://127.0.0.1:7700')
        }
      }
    })
    .use(VueInstantSearch)
    .mount("#app");
</script>

</html>

```

2022-10-18 12:56 UTC, amit-ksh commented
I don't know why it's working, app is importing all the packages correctly but not able to use it plugin as well as the styled components.

2022-10-18 13:26 UTC, bidoubiwa commented
Is it working for you?

2022-10-18 13:32 UTC, amit-ksh commented
No. In the console, warning is logging out for `meilisearch-instantsearch` package

2022-10-18 13:41 UTC, bidoubiwa commented
😕 Tell me if you achieve to make it work. Meanwhile I put this in draft.

2022-10-18 13:43 UTC, amit-ksh commented
OK!

2022-10-21 03:57 UTC, amit-ksh commented
Hey @bidoubiwa! I fix the sample code, would you review it again?

2022-10-26 15:32 UTC, bidoubiwa commented
_This message is sent automatically_

Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

2022-10-26 16:23 UTC, amit-ksh commented
I will definitely give a try

2022-10-27 04:14 UTC, amit-ksh commented
![vue meilisearch app](https://user-images.githubusercontent.com/91947037/198189683-8a033a28-bf7e-437d-af2b-f3a0afc9cf6f.png)

2022-10-27 09:51 UTC, bidoubiwa requested changes

2022-10-27 09:51 UTC, bidoubiwa commented on .code-samples.meilisearch.yaml
> +    <div id="app">
```suggestion
    <div id="app" class="wrapper">
```

2022-10-27 09:51 UTC, bidoubiwa commented on README.md
> +  <header class="header">
Why does this example needed to be changed? It should be as minimal as the one for vue2 with the same style

2022-10-27 09:51 UTC, bidoubiwa commented on .code-samples.meilisearch.yaml
> +        </div>
This does not seem to work. Maybe the previous example from the README in vue3 can help you out

2022-10-27 09:51 UTC, bidoubiwa commented on README.md
> +In the `DebouncedSearchBox.vue` file:
Why did you add this? Was it required?

2022-10-27 13:57 UTC, amit-ksh commented
Made all the requested changes.

2022-10-27 14:28 UTC, bidoubiwa requested changes
Thanks a lot for fixing these bugs so quickly 🙏

Once you're done, can you put the two code samples in a new file named
`.code-samples-vue-3.meilisearch.yaml`
?

2022-10-27 14:28 UTC, bidoubiwa commented on .code-samples.meilisearch.yaml
> +  createApp(App).use(InstantSearch).mount("#app");
```suggestion
  import { createApp } from 'vue';
  import App from './App.vue';
  import InstantSearch from 'vue-instantsearch/vue3/es';
  import "instantsearch.css/themes/algolia-min.css";
  import "@meilisearch/instant-meilisearch/templates/basic_search.css";

  createApp(App).use(InstantSearch).mount('#app');
```

I added the CSS imports here

2022-10-27 14:28 UTC, bidoubiwa commented on .code-samples.meilisearch.yaml
> +      <ais-search-box placeholder="Search here..."></ais-search-box>
```suggestion
      <ais-search-box />
```

2022-10-27 14:28 UTC, bidoubiwa commented on .code-samples.meilisearch.yaml
> +      <ais-configure :hits-per-page.camel="10" />
```suggestion
```

2022-10-27 14:28 UTC, bidoubiwa commented on .code-samples.meilisearch.yaml
> +  import "@meilisearch/instant-meilisearch/templates/basic_search.css";
```suggestion
```

2022-10-27 14:28 UTC, bidoubiwa commented on .code-samples.meilisearch.yaml
> +
```suggestion
```

2022-10-27 14:28 UTC, bidoubiwa commented on .code-samples.meilisearch.yaml
> +    <div id="app">
Not fixed, should have wrapper as class

2022-10-27 14:28 UTC, bidoubiwa commented on README.md
> +import "@meilisearch/instant-meilisearch/templates/basic_search.css";
Could you add 
```
import "instantsearch.css/themes/algolia-min.css";
import "@meilisearch/instant-meilisearch/templates/basic_search.css";
```

In App.vue and remove 
```
import "@meilisearch/instant-meilisearch/templates/basic_search.css";
``` 

from here?

2022-10-27 14:28 UTC, bidoubiwa commented on README.md
>  </style>
this `style` tag can be removed

2022-10-28 04:16 UTC, amit-ksh commented on README.md
>  </style>
Removed!

2022-10-30 17:24 UTC, amit-ksh commented
@bidoubiwa could you review my changes please?

2022-10-31 10:36 UTC, bidoubiwa commented on .code-samples-vue-3.meilisearch.yaml
> +
```suggestion
  </script>
```

2022-10-31 10:36 UTC, bidoubiwa commented on .code-samples-vue-3.meilisearch.yaml
> +
```suggestion
  </script>
```

2022-10-31 10:37 UTC, bidoubiwa reviewed
After this small change I think the PR is good to be merged :)

2022-10-31 12:10 UTC, amit-ksh commented
Done!

2022-10-31 17:25 UTC, bidoubiwa approved these changes
Nice work 🔥 Thanks a lot

2022-10-31 17:25 UTC, merged

2022-10-31 17:25 UTC, bidoubiwa commented
_This message is sent automatically_

Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).