Add explaination on vue3 sample
meilisearch/meilisearch-vue pull request #121
Opened 2022-10-31 17:31 UTC by bidoubiwa

Add missing explaination on vue3 code samples and remove the notification that a vue3 example is on its way

2023-02-15 09:29 UTC, dichotommy commented on .code-samples-vue-3.meilisearch.yaml
> +  The following example uses [Vue 3](https://vuejs.org/) a JavaScript framework for building web user interfaces.
```suggestion
  The following example uses [Vue 3](https://vuejs.org/), a JavaScript framework for building web user interfaces.
```

2023-02-15 14:09 UTC, dichotommy requested changes

2023-02-15 14:09 UTC, dichotommy commented on .code-samples-vue-3.meilisearch.yaml
> +  - To use `instant-meilisearch` with Vue, you must add `<ais-instant-search>`, `<ais-search-box>`, and `<ais-hits>` to your application's HTML. These components are mandatory when generating the`ins
```suggestion
  - To use `instant-meilisearch` with Vue, you must add `<ais-instant-search>`, `<ais-search-box>`, and `<ais-hits>` to your application's HTML. These components are mandatory when generating the `instant-meilisearch` interface
```

2023-02-15 14:09 UTC, dichotommy commented on .code-samples-vue-3.meilisearch.yaml
> +  - The three two`<script src="..">` tags import libraries needed to run `instant-meilisearch` with Vue
```suggestion
  - The three `<script src="..">` tags import libraries needed to run `instant-meilisearch` with Vue
```

2023-02-20 10:16 UTC, dichotommy approved these changes
🏄🏻

2023-02-20 10:17 UTC, dichotommy commented
I do not have write access, so I am requesting a review from Bruno

2023-02-20 12:49 UTC, CaroFG approved these changes

2023-02-20 16:26 UTC, merged